# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto.ai.text_generation import text_generation_pb2 as proto_dot_ai_dot_text__generation_dot_text__generation__pb2


class TextRefinerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.modify_tone = channel.unary_unary(
                '/proto.rpc.ai.text_generation.TextRefiner/modify_tone',
                request_serializer=proto_dot_ai_dot_text__generation_dot_text__generation__pb2.ToneModificationRequest.SerializeToString,
                response_deserializer=proto_dot_ai_dot_text__generation_dot_text__generation__pb2.MeteredTextResponse.FromString,
                )
        self.clarify = channel.unary_unary(
                '/proto.rpc.ai.text_generation.TextRefiner/clarify',
                request_serializer=proto_dot_ai_dot_text__generation_dot_text__generation__pb2.ClarificationRequest.SerializeToString,
                response_deserializer=proto_dot_ai_dot_text__generation_dot_text__generation__pb2.MeteredTextResponse.FromString,
                )


class TextRefinerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def modify_tone(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def clarify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TextRefinerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'modify_tone': grpc.unary_unary_rpc_method_handler(
                    servicer.modify_tone,
                    request_deserializer=proto_dot_ai_dot_text__generation_dot_text__generation__pb2.ToneModificationRequest.FromString,
                    response_serializer=proto_dot_ai_dot_text__generation_dot_text__generation__pb2.MeteredTextResponse.SerializeToString,
            ),
            'clarify': grpc.unary_unary_rpc_method_handler(
                    servicer.clarify,
                    request_deserializer=proto_dot_ai_dot_text__generation_dot_text__generation__pb2.ClarificationRequest.FromString,
                    response_serializer=proto_dot_ai_dot_text__generation_dot_text__generation__pb2.MeteredTextResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.rpc.ai.text_generation.TextRefiner', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TextRefiner(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def modify_tone(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.rpc.ai.text_generation.TextRefiner/modify_tone',
            proto_dot_ai_dot_text__generation_dot_text__generation__pb2.ToneModificationRequest.SerializeToString,
            proto_dot_ai_dot_text__generation_dot_text__generation__pb2.MeteredTextResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def clarify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.rpc.ai.text_generation.TextRefiner/clarify',
            proto_dot_ai_dot_text__generation_dot_text__generation__pb2.ClarificationRequest.SerializeToString,
            proto_dot_ai_dot_text__generation_dot_text__generation__pb2.MeteredTextResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
